version: '3.0'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    volumes:
      - ./neo4j/data:/data
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test
